- Occurs
thread 'async-std/runtime' panicked at 'key not present', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zenoh-0.5.0-beta.9/src/net/routing/network.rs:145:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zenoh-0.5.0-beta.9/src/net/routing/router.rs:381:34
thread 'async-std/runtime' panicked at 'rwlock write lock would result in deadlock', /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/rwlock.rs:88:13

- [2022-05-12T10:39:04Z ERROR zenoh::net::routing::network] [Peers network] Received LinkState
List from unknown link 7647A87724F545D3B8C6792F1A40C066

- thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ZError { kind: SharedMemoryError { descr: "Unable to open SharedMemoryManager: Creating the shared memory failed, os error 24" }, file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zenoh-0.5.0-beta.9/src/net/protocol/io/shm.rs", line: 324, source: None }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/zenoh-0.5.0-beta.9/src/net/transport/unicast/authenticator/shm.rs:143:87
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ZError { kind: SharedMemoryError { descr: "Unable to open SharedMemoryManager: Creating the shared memory failed, os error 24" }, file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/zenoh-0.5.0-beta.9/src/net/protocol/io/shm.rs", line: 324, source: None }

- Comment Zenoh peut prendre 16GB de RAM quand on créer plein de sessions ? (i.e. qu'est ce qui fait qu'une session prend autant de RAM ?)
- Les messages Zenohs restent dans le router à la fin d'une reconf, donc il faudrait les supprimer à chaque fois
- Le nb user des uses ports ne change jamais => pas utile ?
- Faire un test avec des dépendances dans les transitions ?
- Revoir le fonctionnement du waitall, voir si effectivement tous les composants sont bien tous attendus
- Si Exception levée à del_component dans reconf server avec mysql, le client se bloque au moment de faire les déconnexions

Tests connection, deconnection, del: 1 server et 13 clients ça passe, mais avec 1 server et 21 clients certains messages ne sont pas présents dans le routeur, donc soit
pas envoyés, soit pas reçus, soit pas stockés par le router